name: flutter_desktop_cli
version: 1.0.2+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  window_manager: 0.3.0
  get_storage: 2.0.3
  package_info_plus: 3.0.2
  process_run: ^0.12.5+2
  pubspec: ^2.3.0
  version: ^3.0.2
  http: ^0.13.5
  archive: ^3.3.5
  flutter: 
    sdk: flutter
  getwidget: ^3.0.1
  file_picker: ^5.2.5
  filesystem_picker: ^3.1.0
  file_selector: ^0.9.2+2
  path: ^1.8.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lib/assets/files/
